### ISSUE TITLE
Frontend improvement

### ISSUE THREAD

**Issue by Akshat111111** [gSayak/IRCTC-2.0#11]
I can improve the design and layout of your amazing application

**Comment by gSayak** [comment]
Check <a href="https://github.com/gSayak/IRCTC-2.0/issues/10" >#Issue10</a> and you can do that. For, UI you can follow <a href="https://www.behance.net/gallery/123809965/Online-Train-Ticket-Booking-Service-Home-Page/modules/703635547
">this</a> design and work on the TEST branch, also add your name in the contributor list in the readme.

**Comment by Akshat111111** [comment]
I have seen the design,I am working on it

**Comment by gSayak** [comment]
Hey, @Akshat111111 are you working on this? or should I upload a template which you can change accordingly?

**Comment by Akshat111111** [comment]
It will be better if you upload template

**Comment by gSayak** [comment]
okay, will do that

**Comment by gSayak** [comment]
In the design folder, I have added a template(test branch).... incorporate it into react by creating components if u can and work on the test branch

**Comment by Akshat111111** [comment]
sure
